import './globals.css'
import React from 'react'
import { Inter } from 'next/font/google'
import NavigationBar from '@/components/NavigationBar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--inter',
})

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <NavigationBar />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
